name: cd

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: publish
        if: success() && startsWith(github.ref, 'refs/tags/releases/')
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
